### ISSUE TITLE
Adding support for a subtitle

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [talal/ilm#10]
Thank you for the excellent template!

Are there any recommended approaches for how to deal with adding a subtitle to an ilm-templated Typst document? Some other Typst templates have this if you're looking for inspiration (e.g. `dvdtyp` is one). I'm thinking the subtitle would go below the title, maybe not bold and smaller font.

**Comment by Andrew-S-Rosen** [comment]
Fun example :)

And thanks for the reply! Indeed, it is purely subjective. In my case, I am writing a set of notes that is titled "Chemical Reaction Engineering: Lectures Notes for a Graduate-Level Course."

Naturally, putting this all in the title is quite displeasing. Having it in the abstract is viable but does make it a bit less clear. That said, I think there is an element of truth to what you're suggesting --- and I'll definitely try that out!

![image](https://github.com/user-attachments/assets/c3b49e9f-fe9e-45de-91cc-efc9fb11a27a)

P.S. Feel free to close this issue if you wish!

**Comment by talal** [comment]
I initially wrote this template for class notes :)

For reference this is what my title page usually looks:

<img src="https://github.com/user-attachments/assets/5d2c6278-bdef-46be-a6ba-b9f61adaa323"  width="480" />

The name of the course is the title and then I have usually a couple (max 3) sentences with important information such as: name of the professor who taught the course, course code, etc. Everything else goes in the introduction chapter of the notes.

**Comment by Andrew-S-Rosen** [comment]
Looks great! I ended up doing the same and think that looks quite nice.
