### ISSUE TITLE
Typst Universe "create project in app" resulted in an invalid document

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [talal/ilm#11]
I tried using the "Create project in app" feature [here](https://typst.app/universe/package/ilm/), and it generated the following:

```

#show: ilm.with(
  title: "Chemical Reaction Engineering: ",
  authors: (
    (name: "Andrew S. Rosen", affiliation: "Princeton University"),
  ),
  // Insert your abstract after the colon, wrapped in brackets.
  // Example: `abstract: [This is my abstract...]`
  abstract: lorem(59),
)
```
However, I'm not sure this is accurate. For instance, `authors` is not valid.

I know how to properly use the `ilm` template but just wanted to report this.

**Comment by talal** [comment]
Hi,

I can not reproduce this issue. I created new projects using the `Create project in app` button from [here](https://typst.app/universe/package/ilm/) and also the `Start from template` button from the projects dashboard page.

For me, the new projects were created using the [`template/main.typ`](https://github.com/talal/ilm/blob/main/template/main.typ) file that Ilm ships with.

Can you please try creating a new project again and let me know if this issue still persists?

**Comment by Andrew-S-Rosen** [comment]
Oh goodness. This was on me... I must have accidentally clicked "Customize template" on the webpage. Sorry about that!
