### ISSUE TITLE
functionality for creating an Appendix

### ISSUE THREAD

**Issue by CarloLucibello** [talal/ilm#14]
Hi, 
thanks for the nice package, I started to use it to create some lecture notes.

Right now in order to create the appendix for the notes I do the following after the main text

```typst
#counter(heading).update(0)

#set heading(numbering: (..nums) => {
  if nums.pos().len() == 1 {
    return ""
  } 
  let a = nums.pos().slice(1)
  return numbering("A.1.1", ..a)
})

#align(center)[= Appendix]

== Gaussian Integrals  and Error Functions

== TODO
```
with the result
<img width="401" alt="Screenshot 2024-10-09 at 11 56 51" src="https://github.com/user-attachments/assets/cf9cbd6d-f936-4d07-bcae-cc84bbe01c53">

It took me some digging to reach this result, while I think it should be something much more immediate, as it is in latex. 

Would you maybe consider adding some functionality in ilm to reach a similar result?

**Comment by talal** [comment]
Thank you for the suggestion. I'll see what I can do.

**Comment by talal** [comment]
Appendix functionality was added in v1.4.0, kindly wait for https://github.com/typst/packages/pull/1297 to get merged.

For instructions on how to configure the appendix, kindly see the _Appendix_ section in the [example.pdf](https://github.com/talal/ilm/blob/main/example.pdf) file.

**Comment by CarloLucibello** [comment]
The interface for creating an appendix is a little bit awkward:
```typst
#show: ilm.with(
  appendix: (
    enabled: true,
    title: "Appendix", // optional
    heading-numbering-format: "A.1.1.", // optional
    body: [
      = First Appendix
      = Second Appendix
    ],
  ),
)
```
It forces you to pass a big `body` argument or to include as a body an external file. I was hoping for something like `\appendix` in latex, where anything after is considered part of the appendix.

**Comment by talal** [comment]
Unfortunately, I don't have the time to look further into this issue. I added the appendix option as a minimal viable feature that would work.

I will gladly accept a PR that makes this more elegant/intuitive as long as it doesn't break other functionality, e.g. heading numbering before (body) and after (bibliography and indices) appendices work as expected.
