### ISSUE TITLE
Allow for customizing equation numbering

### ISSUE THREAD

**Issue by Epsilon-Delta-N** [talal/ilm#19]
`#set math.equation(numbering: none)` no longer has any effect when using `ilm`. Would it be possible to allow for such adjustments? Thank you!

To reproduce:
```
#import "@preview/ilm:1.4.0": *

#set math.equation(numbering: none)

#show: ilm

$ "equation automatically numbered" $
```

**Comment by talal** [comment]
Since you want to override the default behavior of Ilm therefore you should specify your `set` and `show` rules after the `#show: ilm.with()`. 

For example, try this:

```typst
#import "@preview/ilm:1.4.0": *

#show: ilm.with(
  ...
)

#set math.equation(numbering: none)

$ "equation without numbering $
```

**Comment by Epsilon-Delta-N** [comment]
Thank you talal! I appreciate your efforts in developing this template!
