### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by mescobal** [talal/ilm#4]
The language is harcoded to English (ie. the word "Contents").
It would be nice to change it according to language settings.

**Comment by talal** [comment]
The hard coding of English was resolved in v1.0.0 of the template. Kindly refer to the README for details on how to customize the title of table of contents and other headings such as index of tables.

Here is a tl;dr version: 

```
#show: ilm.with(
  ...

  date-format: "", # specify a custom format string for date
  table-of-contents: outline(title: "Your custom title for TOC"),
  bibliography: bibliography("refs.bib", title: "Custom title"),
  figure-index: (enabled: true, title: "Custom title"),
  table-index: (enabled: true, title: "Custom title"),
  listing-index: (enabled: true, title: "Custom title")
)
```
