### ISSUE TITLE
Included files

### ISSUE THREAD

**Issue by mescobal** [talal/ilm#6]
When working with included files, the page number doesn't show in them.

**Comment by talal** [comment]
I just tested with an included file. It seems to work for me.

Can you give me an example so that I can reproduce the issue that you're facing.

**Comment by mescobal** [comment]
Found the problem.
When i use
`set heading(numbering: none)`
the page number disappears. Don't know if is a bug or not.

**Comment by talal** [comment]
I tried with `#set heading(numbering: none)` and the page numbering still shows as expected.

Try the following:

1. Create a document called `main.typ` with the following document:

    ```typst
    #import "@preview/ilm:1.1.1": *
    
    #show: ilm.with(
      title: [Test Document],
      author: "Max Mustermann",
      date: datetime(year: 2024, month: 03, day: 19),
      abstract: [ #lorem(50) ],
    )
    
    #set heading(numbering: none)
    
    = Heading on main document
    #lorem(50)
    
    #include "external-page.typ"
    ```

2. Create another document called `external-page.typ` with the following content:

    ```typst
    = Heading on external document
    #lorem(50)
    
    #lorem(50)
    ```

3. Compile `main.typ`. You should see page numbering on all pages.
